# Generated by Django 4.1.3 on 2022-12-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_perfil_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.IntegerField(),
        ),
    ]
