# Generated by Django 4.1.3 on 2022-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
