# Generated by Django 4.1.3 on 2022-12-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTarea', '0005_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
