# Generated by Django 4.1.3 on 2022-12-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTarea', '0006_publicacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
