# Generated by Django 4.1.3 on 2022-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTarea', '0007_publicacion_autor_publicacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='cuerpo',
            field=models.TextField(max_length=200),
        ),
    ]
